language: go

go:
  - 1.12.x

env:
  global:
    - GO111MODULE=on

install:
  - go mod download

before_script:
  - go vet ./...
  - go build ./...
  - go test -run xxxx ./...

script:
  - diff -u <(echo -n) <(gofmt -d -s `find . -type f -name '*.go' -not -path "./vendor/*"`)
  - diff -u <(echo -n) <(golint `go list ./... | grep -v /vendor/`)
  - go test -race -short -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
